import 'dotenv/config.js'

export default {
  PROJECT_REPOSITORIES: JSON.parse(process.env.PROJECT_REPOSITORIES),
  PROJECT_SERVER_DIR: process.env.PROJECT_SERVER_DIR,
  PROJECT_CLIENT_DIR: process.env.PROJECT_CLIENT_DIR,
  PROJECT_OUTPUT_DIR: process.env.PROJECT_OUTPUT_DIR,

  CLIENT_NEOFORGE_VERSION: process.env.CLIENT_NEOFORGE_VERSION,
  CLIENT_MINECRAFT_VERSION: process.env.CLIENT_MINECRAFT_VERSION,
  CLIENT_MIN_HEAP_SIZE: process.env.CLIENT_MIN_HEAP_SIZE,
  CLIENT_MAX_HEAP_SIZE: process.env.CLIENT_MAX_HEAP_SIZE,

  SERVER_MIN_HEAP_SIZE: process.env.SERVER_MIN_HEAP_SIZE,
  SERVER_MAX_HEAP_SIZE: process.env.SERVER_MAX_HEAP_SIZE,
  SERVER_PORT: process.env.SERVER_PORT,
  SERVER_HOST: process.env.SERVER_HOST
}